name: "Hola mundo"

on: 
    push:
        branches:
        - main

jobs:
  deploy-codigofacilito:
    runs-on: ubuntu-latest
    steps:
      - run: python3 -m venv venv
      - run: ruby main.rb
      - run: echo "Hola mundo"
      - run: echo "Correr migraciones"
      - run: echo "Generar binario"
      - run: echo "Publicar version"
 
